name: CI-workflow

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Setup golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: task build

      - name: Lint with golangci-lint
        run: golangci-lint run ./...

      - name: Test with go
        run: go test ./... -json > TestResults-${{ matrix.go-version }}.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
